#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Tilemaps;

public static class TEFOReferenceMapGenerator
{
    private const int MapWidth = 120;
    private const int MapHeight = 90;
    private const int Seed = 2507;
    private const string RootName = "TEFO_Map";
    private const string GridName = "Grid";
    private const string DemoMarkerName = "TEFO_Demo_Generated_Metadata";
    private const string DemoPropsName = "TEFO_Demo_Generated_Props";
    private const string DemoBuildingsName = "TEFO_Demo_Generated_Buildings";
    private const string ReportPath = "Assets/Docs/MAP_DEMO_GENERATION_REPORT.md";

    private static readonly string[] LayerNames =
    {
        "Ground",
        "Grass",
        "Forest",
        "Dirt",
        "Road",
        "Road_Marking",
        "Sidewalk",
        "Curb",
        "Sand",
        "Water",
        "Decals_Back",
        "Props_Back",
        "Buildings",
        "Props_Front",
        "Collision"
    };

    private static readonly string[] TileRoots =
    {
        "Assets/Tiles"
    };

    private static readonly string[] PrefabRoots =
    {
        "Assets/Prefabs/Props",
        "Assets/Prefabs/Buildings"
    };

    [MenuItem("TEFO/Map/Demo/Generate Reference Map Demo")]
    public static void GenerateReferenceMapDemo()
    {
        GeneratePolishedReferenceMapDemo();
    }

    [MenuItem("TEFO/Map/Demo/Generate Polished Reference Map Demo")]
    public static void GeneratePolishedReferenceMapDemo()
    {
        DemoReport report = new DemoReport();
        BoundsInt demoBounds = new BoundsInt(0, 0, 0, MapWidth, MapHeight, 1);

        GameObject root = TEFOMapLayerSetupTool.SetupLayerStack(false);
        Transform gridTransform = FindGridTransform(root);
        Dictionary<string, Tilemap> tilemaps = FindTilemaps(gridTransform, report);

        bool isRegeneratingDemo = root.transform.Find(DemoMarkerName) != null;
        if (!isRegeneratingDemo && HasExistingTiles(tilemaps, demoBounds))
        {
            report.SkippedAreas.Add("Generation cancelled because TEFO_Map already has tiles and no demo metadata marker was found. This protects manually painted map layers.");
            WriteReport(report);
            EditorUtility.DisplayDialog(
                "TEFO demo map not generated",
                "Existing map tiles were found, but they were not marked as generated by TEFOReferenceMapGenerator. Clear them manually or keep a generated marker if you want this tool to repaint them.",
                "OK");
            return;
        }

        ClearGeneratedDemo(root, tilemaps, demoBounds);

        AssetLibrary library = AssetLibrary.Load(report);
        TileSet tiles = TileSet.Resolve(library, report);
        MapContext context = new MapContext(tilemaps, library, tiles, report, new System.Random(Seed));

        ReserveSpawn(context);
        PaintBaseTerrain(context);
        PaintForestZone(context);
        PaintRuralVillage(context);
        PaintNatureTransition(context);
        PaintUrbanTown(context);
        PaintBeachAndOcean(context);
        PaintDecals(context);

        Transform propsParent = CreateGeneratedContainer(root.transform, DemoPropsName);
        Transform buildingsParent = CreateGeneratedContainer(root.transform, DemoBuildingsName);
        PlaceForestProps(context, propsParent);
        PlaceVillagePropsAndBuildings(context, propsParent, buildingsParent);
        PlaceTransitionPropsAndLandmarks(context, propsParent, buildingsParent);
        PlaceTownPropsAndBuildings(context, propsParent, buildingsParent);
        PlaceBeachPropsAndBuildings(context, propsParent, buildingsParent);

        MovePlayerAndCamera(report);
        CreateDemoMarker(root.transform);

        foreach (Tilemap tilemap in tilemaps.Values)
        {
            tilemap.CompressBounds();
            EditorUtility.SetDirty(tilemap);
        }

        EditorSceneManager.MarkSceneDirty(root.scene);
        Selection.activeGameObject = root;
        WriteReport(report);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log($"TEFO polished reference demo map generated. Report: {ReportPath}");
    }

    private static void ReserveSpawn(MapContext context)
    {
        ReserveArea(context, 58, 40, 9, 9, 0, false, false, false);
    }

    private static void PaintBaseTerrain(MapContext context)
    {
        for (int x = 0; x < MapWidth; x++)
        {
            for (int y = 0; y < MapHeight; y++)
            {
                PaintCell(context, "Ground", PickRandomTile(context, "Grass", "center"), x, y);
                PaintCell(context, "Grass", PickWeightedTile(context, "Grass", new[] { "center" }, new[] { "flowers", "dense", "rock" }, 12), x, y);
            }
        }

        PaintNoiseVariation(context, 0, 104, 0, MapHeight - 1, "Grass", new[] { "flowers", "dense", "rock" }, 80, 2);
    }

    private static void PaintForestZone(MapContext context)
    {
        for (int y = 0; y < MapHeight; y++)
        {
            int boundary = Mathf.RoundToInt(38f + Mathf.Sin(y * 0.16f) * 4f + Mathf.Sin(y * 0.43f) * 2f + (Noise01(4, y, 1) - 0.5f) * 7f);
            boundary = Mathf.Clamp(boundary, 32, 45);
            for (int x = 0; x <= boundary; x++)
            {
                bool clearing = DistanceToAny(x, y, new Vector2Int(13, 64), new Vector2Int(17, 35), new Vector2Int(31, 54)) < 4f;
                if (clearing && context.Random.NextDouble() < 0.7)
                {
                    PaintCell(context, "Grass", PickRandomTile(context, "Grass", "center"), x, y);
                    continue;
                }

                PaintCell(context, "Forest", PickWeightedTile(context, "Forest", new[] { "floor", "center" }, new[] { "edge", "corner" }, x < 9 ? 8 : 24), x, y);
            }
        }

        PaintWindingPath(context, 2, new Vector2Int(2, 69), new Vector2Int(13, 64), new Vector2Int(23, 55), new Vector2Int(30, 46));
        PaintWindingPath(context, 2, new Vector2Int(3, 34), new Vector2Int(16, 36), new Vector2Int(28, 45), new Vector2Int(42, 47));
        PaintWindingPath(context, 1, new Vector2Int(8, 18), new Vector2Int(17, 27), new Vector2Int(28, 45));

        PaintIrregularBlob(context, "Grass", "Grass", new[] { "center" }, 14, 64, 5, 4, false, false);
        PaintIrregularBlob(context, "Grass", "Grass", new[] { "flowers" }, 32, 53, 4, 3, false, false);
    }

    private static void PaintRuralVillage(MapContext context)
    {
        PaintIrregularBlob(context, "Dirt", "Dirt", new[] { "center" }, 29, 45, 9, 7, false, true);
        PaintIrregularBlob(context, "Dirt", "VillagePlaza", new[] { "stone" }, 29, 45, 4, 3, false, true);

        PaintWindingPath(context, 2, new Vector2Int(29, 45), new Vector2Int(19, 55), new Vector2Int(10, 61));
        PaintWindingPath(context, 2, new Vector2Int(29, 45), new Vector2Int(18, 35), new Vector2Int(14, 25));
        PaintWindingPath(context, 2, new Vector2Int(29, 45), new Vector2Int(41, 46), new Vector2Int(52, 49), new Vector2Int(62, 52));
        PaintWindingPath(context, 1, new Vector2Int(21, 21), new Vector2Int(28, 45), new Vector2Int(36, 63));

        PaintFarmPlot(context, 10, 26, 10, 8);
        PaintFarmPlot(context, 9, 43, 11, 9);
        PaintFarmPlot(context, 20, 57, 9, 7);
        PaintFarmPlot(context, 21, 25, 8, 6);

        PaintNoiseVariation(context, 5, 50, 18, 68, "Grass", new[] { "flowers", "rock", "dense" }, 38, 1);
    }

    private static void PaintNatureTransition(MapContext context)
    {
        for (int x = 40; x <= 62; x++)
        {
            for (int y = 0; y < MapHeight; y++)
            {
                if (Noise01(x, y, 8) > 0.74f)
                {
                    PaintCell(context, "Grass", PickRandomTile(context, "Grass", "flowers"), x, y);
                }
            }
        }

        if (context.Tiles.HasWater)
        {
            PaintIrregularBlob(context, "Water", "Water", new[] { "pond", "water" }, 52, 25, 7, 5, true, false);
            PaintIrregularBlob(context, "Decals_Back", "Water", new[] { "pond", "bank" }, 52, 25, 8, 6, false, false);
        }
        else
        {
            context.Report.SkippedAreas.Add("Transition pond skipped because no water tiles were available.");
        }

        PaintWindingPath(context, 2, new Vector2Int(38, 45), new Vector2Int(47, 47), new Vector2Int(56, 49), new Vector2Int(62, 52));
        PaintWindingPath(context, 1, new Vector2Int(46, 27), new Vector2Int(53, 25), new Vector2Int(60, 34));
        PaintNoiseVariation(context, 42, 61, 5, 85, "Grass", new[] { "dense", "flowers", "rock" }, 26, 2);
    }

    private static void PaintUrbanTown(MapContext context)
    {
        for (int x = 60; x <= 105; x++)
        {
            for (int y = 6; y <= 88; y++)
            {
                if (Noise01(x, y, 12) > 0.68f)
                {
                    PaintCell(context, "Grass", PickRandomTile(context, "Grass", "center"), x, y);
                }
            }
        }

        PaintRoadSegment(context, 82, 8, 82, 88, 5, true);
        PaintRoadSegment(context, 60, 52, 105, 52, 5, true);
        PaintRoadSegment(context, 62, 72, 102, 72, 5, true);
        PaintRoadSegment(context, 64, 32, 104, 32, 5, true);
        PaintRoadSegment(context, 66, 20, 66, 82, 4, true);
        PaintRoadSegment(context, 99, 12, 99, 88, 4, true);
        PaintRoadSegment(context, 73, 32, 73, 44, 3, true);
        PaintRoadSegment(context, 88, 52, 88, 72, 3, true);

        PaintCrosswalk(context, 82, 52);
        PaintCrosswalk(context, 82, 72);
        PaintCrosswalk(context, 82, 32);
        PaintCrosswalk(context, 66, 52);
        PaintCrosswalk(context, 99, 52);
        PaintParkingLot(context, 69, 25, 11, 8);
        PaintTownPlaza(context, 90, 58, 9, 7);

        PaintRoadDetails(context, 60, 105, 8, 88, 90);
    }

    private static void PaintBeachAndOcean(MapContext context)
    {
        for (int y = 0; y < MapHeight; y++)
        {
            int shoreX = Mathf.RoundToInt(113f + Mathf.Sin(y * 0.13f) * 1.7f + Mathf.Sin(y * 0.37f) * 0.9f + (Noise01(114, y, 17) - 0.5f) * 1.5f);
            shoreX = Mathf.Clamp(shoreX, 112, 115);

            for (int x = 105; x < shoreX; x++)
            {
                PaintCell(context, "Sand", PickWeightedTile(context, "Sand", new[] { "center" }, new[] { "shells", "edge" }, 18), x, y);
            }

            if (context.Tiles.HasWater)
            {
                for (int x = shoreX; x < MapWidth; x++)
                {
                    PaintCell(context, "Water", PickWeightedTile(context, "Water", new[] { "ocean", "water" }, new[] { "shore", "foam" }, x == shoreX ? 55 : 8), x, y);
                    context.Water[x, y] = true;
                }
            }

            PaintCell(context, "Decals_Back", PickRandomTile(context, "Water", "foam"), shoreX - 1, y);
            if (context.Tiles.Collision != null && y % 2 == 0)
            {
                PaintCell(context, "Collision", context.Tiles.Collision, shoreX, y);
            }
        }

        PaintIrregularBlob(context, "Sand", "Sand", new[] { "center" }, 110, 10, 5, 4, false, false);
    }

    private static void PaintDecals(MapContext context)
    {
        for (int i = 0; i < 180; i++)
        {
            int x = context.Random.Next(0, 105);
            int y = context.Random.Next(0, MapHeight);
            if (context.Road[x, y] || context.Water[x, y])
            {
                continue;
            }

            TileBase decal = PickRandomFromList(context, context.DecalVariants, context.Tiles.Decal);
            if (decal != null)
            {
                PaintCell(context, "Decals_Back", decal, x, y);
            }
        }
    }

    private static void PaintFarmPlot(MapContext context, int x, int y, int width, int height)
    {
        PaintIrregularBlob(context, "Dirt", "Dirt", new[] { "center" }, x + width / 2, y + height / 2, width / 2 + 1, height / 2 + 1, false, false);
        for (int px = x + 1; px < x + width - 1; px += 2)
        {
            for (int py = y + 1; py < y + height - 1; py++)
            {
                if (context.Random.NextDouble() < 0.75)
                {
                    PaintCell(context, "Decals_Back", PickRandomTile(context, "Grass", "flowers"), px, py);
                }
            }
        }
    }

    private static void PaintParkingLot(MapContext context, int x, int y, int width, int height)
    {
        for (int px = x; px < x + width; px++)
        {
            for (int py = y; py < y + height; py++)
            {
                PaintCell(context, "Road", PickRandomTile(context, "Road", "center"), px, py);
                context.Road[px, py] = true;
            }
        }

        for (int px = x + 1; px < x + width - 1; px += 3)
        {
            PaintLineCells(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "parking", "line", "v"), px, y + 1, px, y + height - 2);
        }
    }

    private static void PaintTownPlaza(MapContext context, int centerX, int centerY, int width, int height)
    {
        PaintIrregularBlob(context, "Dirt", "VillagePlaza", new[] { "stone" }, centerX, centerY, width / 2, height / 2, false, false);
        PaintIrregularBlob(context, "Grass", "Grass", new[] { "flowers" }, centerX + 3, centerY + 2, 3, 2, false, false);
    }

    private static void PaintRoadDetails(MapContext context, int minX, int maxX, int minY, int maxY, int attempts)
    {
        for (int i = 0; i < attempts; i++)
        {
            int x = context.Random.Next(minX, maxX + 1);
            int y = context.Random.Next(minY, maxY + 1);
            if (!IsInsideMap(x, y) || !context.Road[x, y])
            {
                continue;
            }

            TileBase detail = PickRandomTile(context, "Road", "crack", "detail", "drain");
            if (detail != null)
            {
                PaintCell(context, "Decals_Back", detail, x, y);
            }
        }
    }

    private static void PaintNoiseVariation(MapContext context, int minX, int maxX, int minY, int maxY, string category, string[] keywords, int attempts, int radius)
    {
        for (int i = 0; i < attempts; i++)
        {
            int x = context.Random.Next(minX, maxX + 1);
            int y = context.Random.Next(minY, maxY + 1);
            PaintIrregularBlob(context, category == "Water" ? "Water" : "Grass", category, keywords, x, y, radius + context.Random.Next(0, 2), radius, category == "Water", false);
        }
    }

    private static void PaintIrregularBlob(MapContext context, string layerName, string tileCategory, string[] keywords, int centerX, int centerY, int radiusX, int radiusY, bool markWater, bool markPath)
    {
        for (int x = centerX - radiusX - 2; x <= centerX + radiusX + 2; x++)
        {
            for (int y = centerY - radiusY - 2; y <= centerY + radiusY + 2; y++)
            {
                if (!IsInsideMap(x, y))
                {
                    continue;
                }

                float nx = (x - centerX) / Mathf.Max(1f, radiusX);
                float ny = (y - centerY) / Mathf.Max(1f, radiusY);
                float distance = Mathf.Sqrt(nx * nx + ny * ny);
                float edge = 1f + (Noise01(x, y, centerX + centerY) - 0.5f) * 0.45f;
                if (distance > edge)
                {
                    continue;
                }

                PaintCell(context, layerName, PickRandomTile(context, tileCategory, keywords), x, y);
                if (markWater)
                {
                    context.Water[x, y] = true;
                }

                if (markPath)
                {
                    context.MainPath[x, y] = true;
                }
            }
        }
    }

    private static void PaintWindingPath(MapContext context, int radius, params Vector2Int[] points)
    {
        int globalStep = 0;
        for (int i = 0; i < points.Length - 1; i++)
        {
            Vector2 start = points[i];
            Vector2 end = points[i + 1];
            Vector2 direction = end - start;
            Vector2 normal = direction.sqrMagnitude > 0.01f ? new Vector2(-direction.y, direction.x).normalized : Vector2.up;
            int steps = Mathf.Max(1, Mathf.RoundToInt(direction.magnitude * 3f));

            for (int step = 0; step <= steps; step++)
            {
                float t = step / (float)steps;
                float wobble = Mathf.Sin((globalStep + Seed) * 0.31f) * 1.15f + Mathf.Sin((globalStep + Seed) * 0.11f) * 0.7f;
                Vector2 point = Vector2.Lerp(start, end, t) + normal * wobble;
                int x = Mathf.RoundToInt(point.x);
                int y = Mathf.RoundToInt(point.y);
                PaintBrush(context, "Dirt", x, y, radius + (Noise01(x, y, 23) > 0.72f ? 1 : 0), "Dirt", new[] { "center", "path" }, false, true);
                globalStep++;
            }
        }
    }

    private static void PaintRoadSegment(MapContext context, int x0, int y0, int x1, int y1, int width, bool withSidewalk)
    {
        bool vertical = x0 == x1;
        int half = width / 2;
        int minX = Mathf.Min(x0, x1);
        int maxX = Mathf.Max(x0, x1);
        int minY = Mathf.Min(y0, y1);
        int maxY = Mathf.Max(y0, y1);

        if (vertical)
        {
            for (int y = minY; y <= maxY; y++)
            {
                for (int dx = -half; dx <= half; dx++)
                {
                    int x = x0 + dx;
                    PaintRoadCell(context, x, y, "v");
                }

                if (withSidewalk)
                {
                    PaintCell(context, "Curb", PickRandomTile(context, "Curb", "left"), x0 - half - 1, y);
                    PaintCell(context, "Curb", PickRandomTile(context, "Curb", "right"), x0 + half + 1, y);
                    PaintCell(context, "Sidewalk", PickRandomTile(context, "Sidewalk", "center"), x0 - half - 2, y);
                    PaintCell(context, "Sidewalk", PickRandomTile(context, "Sidewalk", "center"), x0 + half + 2, y);
                }

                if (y % 5 == 0)
                {
                    PaintCell(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "line", "v"), x0, y);
                }
            }
        }
        else
        {
            for (int x = minX; x <= maxX; x++)
            {
                for (int dy = -half; dy <= half; dy++)
                {
                    int y = y0 + dy;
                    PaintRoadCell(context, x, y, "h");
                }

                if (withSidewalk)
                {
                    PaintCell(context, "Curb", PickRandomTile(context, "Curb", "bottom"), x, y0 - half - 1);
                    PaintCell(context, "Curb", PickRandomTile(context, "Curb", "top"), x, y0 + half + 1);
                    PaintCell(context, "Sidewalk", PickRandomTile(context, "Sidewalk", "center"), x, y0 - half - 2);
                    PaintCell(context, "Sidewalk", PickRandomTile(context, "Sidewalk", "center"), x, y0 + half + 2);
                }

                if (x % 5 == 0)
                {
                    PaintCell(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "line", "h"), x, y0);
                }
            }
        }
    }

    private static void PaintRoadCell(MapContext context, int x, int y, string orientation)
    {
        if (!IsInsideMap(x, y))
        {
            return;
        }

        TileBase road = PickWeightedTile(context, "Road", new[] { "straight", orientation }, new[] { "center", "detail" }, 25);
        PaintCell(context, "Road", road, x, y);
        context.Road[x, y] = true;
        context.MainPath[x, y] = true;
    }

    private static void PaintCrosswalk(MapContext context, int centerX, int centerY)
    {
        for (int dx = -4; dx <= 4; dx++)
        {
            PaintCell(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "crosswalk", "h"), centerX + dx, centerY - 4);
            PaintCell(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "crosswalk", "h"), centerX + dx, centerY + 4);
        }

        for (int dy = -4; dy <= 4; dy++)
        {
            PaintCell(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "crosswalk", "v"), centerX - 4, centerY + dy);
            PaintCell(context, "Road_Marking", PickRandomTile(context, "Road_Marking", "crosswalk", "v"), centerX + 4, centerY + dy);
        }
    }

    private static void PaintLineCells(MapContext context, string layerName, TileBase tile, int x0, int y0, int x1, int y1)
    {
        int dx = Math.Sign(x1 - x0);
        int dy = Math.Sign(y1 - y0);
        int x = x0;
        int y = y0;
        PaintCell(context, layerName, tile, x, y);
        while (x != x1 || y != y1)
        {
            if (x != x1)
            {
                x += dx;
            }

            if (y != y1)
            {
                y += dy;
            }

            PaintCell(context, layerName, tile, x, y);
        }
    }

    private static void PaintBrush(MapContext context, string layerName, int centerX, int centerY, int radius, string tileCategory, string[] keywords, bool markWater, bool markPath)
    {
        int r2 = radius * radius;
        for (int x = centerX - radius; x <= centerX + radius; x++)
        {
            for (int y = centerY - radius; y <= centerY + radius; y++)
            {
                int dx = x - centerX;
                int dy = y - centerY;
                if (dx * dx + dy * dy > r2 || !IsInsideMap(x, y))
                {
                    continue;
                }

                PaintCell(context, layerName, PickRandomTile(context, tileCategory, keywords), x, y);
                if (markWater)
                {
                    context.Water[x, y] = true;
                }

                if (markPath)
                {
                    context.MainPath[x, y] = true;
                }
            }
        }
    }

    private static void PaintCell(MapContext context, string layerName, TileBase tile, int x, int y)
    {
        if (tile == null || !IsInsideMap(x, y))
        {
            return;
        }

        if (!context.Tilemaps.TryGetValue(layerName, out Tilemap tilemap) || tilemap == null)
        {
            context.Report.RecordMissingLayer(layerName);
            return;
        }

        Vector3Int position = new Vector3Int(x, y, 0);
        tilemap.SetTile(position, tile);
        context.Report.RecordTilePainted(layerName, position);
    }

    private static TileBase PickRandomTile(MapContext context, string category, params string[] keywords)
    {
        List<TileBase> candidates = context.Library.FindTiles(category, keywords);
        if (candidates.Count == 0)
        {
            TileBase fallback = context.Tiles.GetFallbackTile(category);
            if (fallback == null)
            {
                context.Report.RecordMissingTile(category, string.Join(" ", keywords));
            }

            return fallback;
        }

        if (candidates.Count == 1)
        {
            context.Report.RecordSingleVariant(category, keywords);
        }

        return candidates[context.Random.Next(candidates.Count)];
    }

    private static TileBase PickWeightedTile(MapContext context, string category, string[] primaryKeywords, string[] variationKeywords, int variationPercent)
    {
        if (context.Random.Next(100) < variationPercent)
        {
            TileBase variation = PickRandomTile(context, category, variationKeywords);
            if (variation != null)
            {
                return variation;
            }
        }

        TileBase primary = PickRandomTile(context, category, primaryKeywords);
        return primary ?? PickRandomTile(context, category);
    }

    private static TileBase PickRandomFromList(MapContext context, List<TileBase> tiles, TileBase fallback)
    {
        if (tiles.Count == 0)
        {
            return fallback;
        }

        return tiles[context.Random.Next(tiles.Count)];
    }

    private static void PlaceForestProps(MapContext context, Transform propsParent)
    {
        List<Vector2Int> clusters = new List<Vector2Int>
        {
            new Vector2Int(7, 72),
            new Vector2Int(10, 48),
            new Vector2Int(13, 20),
            new Vector2Int(27, 75),
            new Vector2Int(34, 30)
        };

        foreach (Vector2Int cluster in clusters)
        {
            int count = cluster.x < 15 ? 42 : 26;
            for (int i = 0; i < count; i++)
            {
                int x = Mathf.Clamp(Mathf.RoundToInt(cluster.x + NextGaussian(context.Random) * 6f), 1, 43);
                int y = Mathf.Clamp(Mathf.RoundToInt(cluster.y + NextGaussian(context.Random) * 8f), 2, 87);
                PrefabChoice tree = PickPrefab(context, PrefabKind.Prop, "forest tree", "tree", i % 3 == 0 ? "pine" : "oak");
                PlacePrefabIfAvailable(context, tree, propsParent, x, y, false, false, false, 0);
            }
        }

        for (int i = 0; i < 80; i++)
        {
            int x = context.Random.Next(2, 50);
            int y = context.Random.Next(3, 87);
            PrefabChoice prop = i % 4 == 0
                ? PickPrefab(context, PrefabKind.Prop, "forest rock", "rock")
                : i % 4 == 1
                    ? PickPrefab(context, PrefabKind.Prop, "forest stump", "stump", "log")
                    : PickPrefab(context, PrefabKind.Prop, "forest bush", "bush", "grass_tuft", "flower");
            PlacePrefabIfAvailable(context, prop, propsParent, x, y, false, false, false, 0);
        }
    }

    private static void PlaceVillagePropsAndBuildings(MapContext context, Transform propsParent, Transform buildingsParent)
    {
        Vector2Int[] housePositions =
        {
            new Vector2Int(19, 53),
            new Vector2Int(25, 61),
            new Vector2Int(37, 58),
            new Vector2Int(41, 47),
            new Vector2Int(20, 35),
            new Vector2Int(35, 31),
            new Vector2Int(31, 67)
        };

        for (int i = 0; i < housePositions.Length; i++)
        {
            PrefabChoice house = PickPrefab(context, PrefabKind.Building, "village house", "village", "house");
            PlacePrefabIfAvailable(context, house, buildingsParent, housePositions[i].x + context.Random.Next(-1, 2), housePositions[i].y + context.Random.Next(-1, 2), true, false, false, 1);
        }

        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, "village barn", "barn"), buildingsParent, 15, 23, true, false, false, 1);
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "village center well", "well", "fountain", "statue"), propsParent, 29, 45, false, false, true, 0);

        Vector2Int[] farmCenters =
        {
            new Vector2Int(14, 30),
            new Vector2Int(14, 48),
            new Vector2Int(24, 61),
            new Vector2Int(24, 28)
        };

        foreach (Vector2Int center in farmCenters)
        {
            PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "crop field", "crop", "field"), propsParent, center.x, center.y, false, false, false, 1);
            PlaceFenceLine(context, propsParent, center.x - 5, center.y - 4, center.x + 5, center.y - 4);
            PlaceFenceLine(context, propsParent, center.x - 5, center.y + 4, center.x + 5, center.y + 4);
        }

        for (int i = 0; i < 42; i++)
        {
            int x = context.Random.Next(12, 48);
            int y = context.Random.Next(22, 67);
            PrefabChoice prop = i % 5 == 0
                ? PickPrefab(context, PrefabKind.Prop, "village rock", "rock")
                : i % 5 == 1
                    ? PickPrefab(context, PrefabKind.Prop, "village log", "log", "stump")
                    : PickPrefab(context, PrefabKind.Prop, "village bush or flower", "bush", "flower", "grass_tuft");
            PlacePrefabIfAvailable(context, prop, propsParent, x, y, false, false, false, 0);
        }
    }

    private static void PlaceTransitionPropsAndLandmarks(MapContext context, Transform propsParent, Transform buildingsParent)
    {
        for (int i = 0; i < 45; i++)
        {
            int x = context.Random.Next(42, 62);
            int y = context.Random.Next(5, 85);
            PrefabChoice prop = i % 3 == 0
                ? PickPrefab(context, PrefabKind.Prop, "transition tree", "tree")
                : i % 3 == 1
                    ? PickPrefab(context, PrefabKind.Prop, "transition rock", "rock")
                    : PickPrefab(context, PrefabKind.Prop, "transition bush", "bush", "grass_tuft");
            PlacePrefabIfAvailable(context, prop, propsParent, x, y, false, false, false, 0);
        }

        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, "bridge", "bridge"), buildingsParent, 54, 25, true, true, true, 0);
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "dock bridge piece", "dock", "bridge"), propsParent, 54, 25, false, true, true, 0);
    }

    private static void PlaceTownPropsAndBuildings(MapContext context, Transform propsParent, Transform buildingsParent)
    {
        PaintBuildingBlock(context, buildingsParent, 73, 61, "shop", "shop", "store");
        PaintBuildingBlock(context, buildingsParent, 91, 63, "shop", "shop", "store");
        PaintBuildingBlock(context, buildingsParent, 73, 78, "town house", "town", "house");
        PaintBuildingBlock(context, buildingsParent, 92, 79, "town house", "town", "house");
        PaintBuildingBlock(context, buildingsParent, 74, 42, "town house", "town", "house");
        PaintBuildingBlock(context, buildingsParent, 91, 42, "town house", "town", "house");
        PaintBuildingBlock(context, buildingsParent, 102, 24, "town house", "town", "house");
        PaintBuildingBlock(context, buildingsParent, 76, 20, "town house", "town", "house");

        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, "parking lot", "parking"), buildingsParent, 75, 29, true, false, false, 0);
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, "plaza monument", "monument", "plaza"), buildingsParent, 91, 58, true, false, true, 0);
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "town fountain", "fountain", "statue"), propsParent, 88, 59, false, false, true, 0);

        for (int i = 0; i < 74; i++)
        {
            Vector2Int position = PickTownStreetPropPosition(context);
            PrefabChoice prop = i % 6 == 0
                ? PickPrefab(context, PrefabKind.Prop, "lamp", "lamp")
                : i % 6 == 1
                    ? PickPrefab(context, PrefabKind.Prop, "bench", "bench")
                    : i % 6 == 2
                        ? PickPrefab(context, PrefabKind.Prop, "mailbox", "mailbox")
                        : i % 6 == 3
                            ? PickPrefab(context, PrefabKind.Prop, "trash", "trash")
                            : i % 6 == 4
                                ? PickPrefab(context, PrefabKind.Prop, "sign", "sign")
                                : PickPrefab(context, PrefabKind.Prop, "crate barrel", "crate", "barrel");
            PlacePrefabIfAvailable(context, prop, propsParent, position.x, position.y, false, false, false, 0);
        }

        PlaceFenceLine(context, propsParent, 69, 76, 78, 76);
        PlaceFenceLine(context, propsParent, 87, 38, 96, 38);
    }

    private static void PaintBuildingBlock(MapContext context, Transform buildingsParent, int x, int y, string label, params string[] tokens)
    {
        PaintIrregularBlob(context, "Grass", "Grass", new[] { "center" }, x, y, 5, 4, false, false);
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, label, tokens), buildingsParent, x, y, true, false, false, 1);
    }

    private static void PlaceBeachPropsAndBuildings(MapContext context, Transform propsParent, Transform buildingsParent)
    {
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, "lighthouse", "lighthouse"), buildingsParent, 110, 10, true, false, false, 1);
        PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Building, "beach hut", "beach", "hut"), buildingsParent, 108, 28, true, false, false, 1);

        int[] beachYs = { 16, 22, 35, 43, 56, 64, 78, 84 };
        foreach (int y in beachYs)
        {
            PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "palm", "palm"), propsParent, 107 + context.Random.Next(0, 4), y, false, false, false, 0);
        }

        for (int i = 0; i < 18; i++)
        {
            int x = context.Random.Next(106, 113);
            int y = context.Random.Next(14, 82);
            PrefabChoice prop = i % 3 == 0
                ? PickPrefab(context, PrefabKind.Prop, "beach umbrella", "umbrella")
                : i % 3 == 1
                    ? PickPrefab(context, PrefabKind.Prop, "beach chair", "chair")
                    : PickPrefab(context, PrefabKind.Prop, "beach towel", "towel", "bench", "sign");
            PlacePrefabIfAvailable(context, prop, propsParent, x, y, false, false, false, 0);
        }

        for (int x = 112; x <= 116; x++)
        {
            PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "dock", "dock", x == 112 ? "end" : "straight"), propsParent, x, 70, false, true, true, 0);
        }

        for (int i = 0; i < 14; i++)
        {
            PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "shore rock", "rock"), propsParent, context.Random.Next(107, 114), context.Random.Next(5, 86), false, false, false, 0);
        }
    }

    private static Vector2Int PickTownStreetPropPosition(MapContext context)
    {
        for (int attempt = 0; attempt < 80; attempt++)
        {
            int x = context.Random.Next(61, 105);
            int y = context.Random.Next(10, 86);
            if (IsNearRoad(context, x, y) && !context.Road[x, y] && !context.Water[x, y])
            {
                return new Vector2Int(x, y);
            }
        }

        return new Vector2Int(context.Random.Next(61, 105), context.Random.Next(10, 86));
    }

    private static bool IsNearRoad(MapContext context, int x, int y)
    {
        for (int dx = -2; dx <= 2; dx++)
        {
            for (int dy = -2; dy <= 2; dy++)
            {
                int px = x + dx;
                int py = y + dy;
                if (IsInsideMap(px, py) && context.Road[px, py])
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static void PlaceFenceLine(MapContext context, Transform parent, int x0, int y0, int x1, int y1)
    {
        int dx = Math.Sign(x1 - x0);
        int dy = Math.Sign(y1 - y0);
        int x = x0;
        int y = y0;
        while (true)
        {
            PlacePrefabIfAvailable(context, PickPrefab(context, PrefabKind.Prop, "fence", "fence", dx != 0 ? "h" : "v"), parent, x, y, false, false, false, 0);
            if (x == x1 && y == y1)
            {
                break;
            }

            if (x != x1)
            {
                x += dx;
            }

            if (y != y1)
            {
                y += dy;
            }
        }
    }

    private static PrefabChoice PickPrefab(MapContext context, PrefabKind kind, string label, params string[] tokens)
    {
        List<PrefabChoice> choices = context.Library.FindPrefabs(kind, tokens);
        if (choices.Count == 0)
        {
            context.Report.RecordMissingPrefab(kind, label);
            return PrefabChoice.Invalid;
        }

        if (choices.Count == 1)
        {
            context.Report.RecordSinglePrefabVariant(kind, label);
        }

        return choices[context.Random.Next(choices.Count)];
    }

    private static bool PlacePrefabIfAvailable(MapContext context, PrefabChoice choice, Transform parent, int x, int y, bool isBuilding, bool allowWater, bool allowMainPath, int margin)
    {
        if (!choice.IsValid || parent == null)
        {
            return false;
        }

        Vector2Int footprint = GetPrefabFootprint(choice.Prefab, isBuilding);
        if (!IsAreaClear(context, x, y, footprint.x, footprint.y, margin, allowWater, allowMainPath))
        {
            context.Report.SkippedPlacements.Add($"{choice.Path} at {x},{y}: blocked by road, water, path, spawn, or another generated object.");
            return false;
        }

        GameObject instance = PrefabUtility.InstantiatePrefab(choice.Prefab) as GameObject;
        if (instance == null)
        {
            context.Report.Warnings.Add($"Could not instantiate prefab: {choice.Path}");
            return false;
        }

        Undo.RegisterCreatedObjectUndo(instance, $"Place {choice.Prefab.name}");
        Undo.SetTransformParent(instance.transform, parent, $"Parent {choice.Prefab.name}");
        instance.transform.position = new Vector3(x + 0.5f, y + 0.5f, instance.transform.position.z);
        instance.transform.rotation = Quaternion.identity;
        instance.transform.localScale = Vector3.one;

        MarkOccupied(context, x, y, footprint.x, footprint.y, margin);
        if (isBuilding)
        {
            context.Report.BuildingsPlaced++;
            context.Report.Increment(context.Report.BuildingsPlacedByCategory, choice.Category);
            if (!choice.HasCollider)
            {
                PaintBuildingCollision(context, x, y, footprint.x, footprint.y);
            }
        }
        else
        {
            context.Report.PropsPlaced++;
            context.Report.Increment(context.Report.PropsPlacedByCategory, choice.Category);
        }

        return true;
    }

    private static Vector2Int GetPrefabFootprint(GameObject prefab, bool isBuilding)
    {
        SpriteRenderer renderer = prefab.GetComponent<SpriteRenderer>();
        if (renderer == null || renderer.sprite == null)
        {
            return isBuilding ? new Vector2Int(3, 3) : new Vector2Int(1, 1);
        }

        Vector3 size = renderer.sprite.bounds.size;
        int width = Mathf.Clamp(Mathf.CeilToInt(size.x), isBuilding ? 3 : 1, isBuilding ? 8 : 3);
        int height = Mathf.Clamp(Mathf.CeilToInt(size.y), isBuilding ? 3 : 1, isBuilding ? 8 : 3);
        return new Vector2Int(width, height);
    }

    private static bool IsAreaClear(MapContext context, int centerX, int centerY, int width, int height, int margin, bool allowWater, bool allowMainPath)
    {
        int left = centerX - width / 2 - margin;
        int right = centerX + (width - 1) / 2 + margin;
        int bottom = centerY - height / 2 - margin;
        int top = centerY + (height - 1) / 2 + margin;

        for (int x = left; x <= right; x++)
        {
            for (int y = bottom; y <= top; y++)
            {
                if (!IsInsideMap(x, y) || IsNearSpawn(x, y))
                {
                    return false;
                }

                if (context.Occupied[x, y] || context.Road[x, y] || (!allowWater && context.Water[x, y]) || (!allowMainPath && context.MainPath[x, y]))
                {
                    return false;
                }
            }
        }

        return true;
    }

    private static void ReserveArea(MapContext context, int centerX, int centerY, int width, int height, int margin, bool allowWater, bool allowMainPath, bool allowRoad)
    {
        int left = centerX - width / 2 - margin;
        int right = centerX + (width - 1) / 2 + margin;
        int bottom = centerY - height / 2 - margin;
        int top = centerY + (height - 1) / 2 + margin;

        for (int x = left; x <= right; x++)
        {
            for (int y = bottom; y <= top; y++)
            {
                if (!IsInsideMap(x, y))
                {
                    continue;
                }

                context.Occupied[x, y] = true;
                if (!allowWater)
                {
                    context.Water[x, y] = false;
                }

                if (!allowMainPath)
                {
                    context.MainPath[x, y] = false;
                }

                if (!allowRoad)
                {
                    context.Road[x, y] = false;
                }
            }
        }
    }

    private static void MarkOccupied(MapContext context, int centerX, int centerY, int width, int height, int margin)
    {
        int left = centerX - width / 2 - margin;
        int right = centerX + (width - 1) / 2 + margin;
        int bottom = centerY - height / 2 - margin;
        int top = centerY + (height - 1) / 2 + margin;

        for (int x = left; x <= right; x++)
        {
            for (int y = bottom; y <= top; y++)
            {
                if (IsInsideMap(x, y))
                {
                    context.Occupied[x, y] = true;
                }
            }
        }
    }

    private static void PaintCollisionPoint(MapContext context, int x, int y)
    {
        if (context.Tiles.Collision != null && IsInsideMap(x, y) && !context.Road[x, y] && !context.MainPath[x, y])
        {
            PaintCell(context, "Collision", context.Tiles.Collision, x, y);
        }
    }

    private static void PaintBuildingCollision(MapContext context, int x, int y, int width, int height)
    {
        if (context.Tiles.Collision == null)
        {
            return;
        }

        int left = x - width / 2;
        int bottom = y - height / 2;
        for (int px = left; px < left + width; px++)
        {
            for (int py = bottom; py < bottom + height; py++)
            {
                if (IsInsideMap(px, py) && !context.Road[px, py] && !context.MainPath[px, py])
                {
                    PaintCell(context, "Collision", context.Tiles.Collision, px, py);
                }
            }
        }
    }

    private static Transform FindGridTransform(GameObject root)
    {
        Transform grid = root.transform.Find(GridName);
        return grid != null ? grid : root.transform;
    }

    private static Dictionary<string, Tilemap> FindTilemaps(Transform gridTransform, DemoReport report)
    {
        Dictionary<string, Tilemap> tilemaps = new Dictionary<string, Tilemap>(StringComparer.OrdinalIgnoreCase);
        foreach (string layerName in LayerNames)
        {
            Transform child = gridTransform.Find(layerName);
            Tilemap tilemap = child == null ? null : child.GetComponent<Tilemap>();
            if (tilemap == null)
            {
                report.Warnings.Add($"Tilemap layer missing: {layerName}");
                continue;
            }

            tilemaps[layerName] = tilemap;
        }

        return tilemaps;
    }

    private static bool HasExistingTiles(Dictionary<string, Tilemap> tilemaps, BoundsInt bounds)
    {
        foreach (Tilemap tilemap in tilemaps.Values)
        {
            foreach (Vector3Int position in bounds.allPositionsWithin)
            {
                if (tilemap.HasTile(position))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static void ClearGeneratedDemo(GameObject root, Dictionary<string, Tilemap> tilemaps, BoundsInt bounds)
    {
        foreach (Tilemap tilemap in tilemaps.Values)
        {
            foreach (Vector3Int position in bounds.allPositionsWithin)
            {
                tilemap.SetTile(position, null);
            }
        }

        DestroyGeneratedChild(root.transform, DemoPropsName);
        DestroyGeneratedChild(root.transform, DemoBuildingsName);
        DestroyGeneratedChild(root.transform, DemoMarkerName);
    }

    private static void DestroyGeneratedChild(Transform root, string childName)
    {
        Transform child = root.Find(childName);
        if (child != null)
        {
            Undo.DestroyObjectImmediate(child.gameObject);
        }
    }

    private static Transform CreateGeneratedContainer(Transform root, string containerName)
    {
        GameObject container = new GameObject(containerName);
        Undo.RegisterCreatedObjectUndo(container, $"Create {containerName}");
        Undo.SetTransformParent(container.transform, root, $"Parent {containerName}");
        container.transform.localPosition = Vector3.zero;
        container.transform.localRotation = Quaternion.identity;
        container.transform.localScale = Vector3.one;
        return container.transform;
    }

    private static void CreateDemoMarker(Transform root)
    {
        GameObject marker = new GameObject(DemoMarkerName);
        marker.hideFlags = HideFlags.NotEditable;
        Undo.RegisterCreatedObjectUndo(marker, "Create TEFO demo marker");
        Undo.SetTransformParent(marker.transform, root, "Parent TEFO demo marker");
        marker.transform.localPosition = Vector3.zero;
    }

    private static void MovePlayerAndCamera(DemoReport report)
    {
        Vector3 spawn = new Vector3(58f, 40f, 0f);
        GameObject player = GameObject.Find("Player");
        if (player == null)
        {
            try
            {
                player = GameObject.FindWithTag("Player");
            }
            catch (UnityException)
            {
                player = null;
            }
        }

        if (player != null)
        {
            Undo.RecordObject(player.transform, "Move TEFO player to polished demo spawn");
            player.transform.position = new Vector3(spawn.x, spawn.y, player.transform.position.z);
            report.SceneObjectsMoved.Add("Player moved to x=58, y=40.");
        }
        else
        {
            report.Warnings.Add("Player object not found; spawn was not moved.");
        }

        Camera camera = Camera.main;
        if (camera == null)
        {
            GameObject cameraObject = GameObject.Find("Main Camera");
            camera = cameraObject == null ? null : cameraObject.GetComponent<Camera>();
        }

        if (camera != null)
        {
            Undo.RecordObject(camera.transform, "Move TEFO camera to polished demo spawn");
            camera.transform.position = new Vector3(spawn.x, spawn.y, camera.transform.position.z);
            report.SceneObjectsMoved.Add("Main Camera moved near player spawn.");
        }
        else
        {
            report.Warnings.Add("Main Camera not found; camera was not moved.");
        }
    }

    private static float Noise01(int x, int y, int salt)
    {
        float value = Mathf.Sin((x * 12.9898f + y * 78.233f + salt * 37.719f + Seed) * 0.0174533f) * 43758.5453f;
        return value - Mathf.Floor(value);
    }

    private static float NextGaussian(System.Random random)
    {
        double u1 = 1.0 - random.NextDouble();
        double u2 = 1.0 - random.NextDouble();
        return (float)(Math.Sqrt(-2.0 * Math.Log(u1)) * Math.Sin(2.0 * Math.PI * u2));
    }

    private static float DistanceToAny(int x, int y, params Vector2Int[] points)
    {
        float best = float.MaxValue;
        foreach (Vector2Int point in points)
        {
            float distance = Vector2Int.Distance(new Vector2Int(x, y), point);
            if (distance < best)
            {
                best = distance;
            }
        }

        return best;
    }

    private static bool IsNearSpawn(int x, int y)
    {
        return Mathf.Abs(x - 58) <= 4 && Mathf.Abs(y - 40) <= 4;
    }

    private static bool IsInsideMap(int x, int y)
    {
        return x >= 0 && x < MapWidth && y >= 0 && y < MapHeight;
    }

    private static void WriteReport(DemoReport report)
    {
        Directory.CreateDirectory("Assets/Docs");

        StringBuilder builder = new StringBuilder();
        builder.AppendLine("# TEFO Map Demo Generation Report");
        builder.AppendLine();
        builder.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        builder.AppendLine($"Seed: {Seed}");
        builder.AppendLine($"Map size: {MapWidth}x{MapHeight} tiles");
        builder.AppendLine("Generator style: polished organic reference map");
        builder.AppendLine("Expected tile size: 32x32 px, PPU 32, 1 tile = 1 Unity unit");
        builder.AppendLine();
        builder.AppendLine("## Summary");
        builder.AppendLine();
        builder.AppendLine($"- Props placed: {report.PropsPlaced}");
        builder.AppendLine($"- Buildings placed: {report.BuildingsPlaced}");
        builder.AppendLine($"- Skipped placements: {report.SkippedPlacements.Count}");
        builder.AppendLine($"- Missing important categories: {report.MissingImportantCategories.Distinct().Count()}");
        builder.AppendLine();
        AppendCountMap(builder, "Tiles Painted Per Layer", report.TilesPaintedByLayer.ToDictionary(pair => pair.Key, pair => pair.Value.Count, StringComparer.OrdinalIgnoreCase));
        AppendCountMap(builder, "Props Placed By Category", report.PropsPlacedByCategory);
        AppendCountMap(builder, "Buildings Placed By Category", report.BuildingsPlacedByCategory);
        AppendList(builder, "Available Tile Categories", report.AvailableTileCategories);
        AppendList(builder, "Available Prefab Categories", report.AvailablePrefabCategories);
        AppendList(builder, "Missing Important Categories", report.MissingImportantCategories);
        AppendList(builder, "Fallback Tiles Used", report.FallbackTilesUsed);
        AppendList(builder, "Missing Tile Categories", report.MissingTileCategories);
        AppendList(builder, "Missing Prop/Building Categories", report.MissingPrefabCategories);
        AppendList(builder, "Skipped Placements", report.SkippedPlacements);
        AppendList(builder, "Skipped Areas", report.SkippedAreas);
        AppendList(builder, "Scene Objects Moved", report.SceneObjectsMoved);
        AppendList(builder, "Warnings", report.Warnings);

        builder.AppendLine("## Manual Polish Notes");
        builder.AppendLine();
        builder.AppendLine("- The map is intentionally generated as a playable reference pass, not a final hand-painted scene.");
        builder.AppendLine("- Collision is limited if `Assets/Tiles/Collision` is empty; add a collision tile and rerun if water/building blocking needs tilemap collision.");
        builder.AppendLine("- Roads now use fewer rectangular blocks, but road corners/intersections can still be hand-polished with exact corner tiles.");
        builder.AppendLine("- The village center fountain-area PNG was flagged as a spritesheet by ingest, so the generator uses smaller well/fountain/statue prefabs when available.");
        builder.AppendLine("- Save the scene after reviewing the generated `TEFO_Map` hierarchy.");
        builder.AppendLine();

        File.WriteAllText(ReportPath, builder.ToString(), Encoding.UTF8);
        AssetDatabase.ImportAsset(ReportPath);
    }

    private static void AppendCountMap(StringBuilder builder, string title, Dictionary<string, int> counts)
    {
        builder.AppendLine($"## {title}");
        builder.AppendLine();
        if (counts.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (KeyValuePair<string, int> pair in counts.OrderBy(pair => pair.Key))
            {
                builder.AppendLine($"- {pair.Key}: {pair.Value}");
            }
        }

        builder.AppendLine();
    }

    private static void AppendList(StringBuilder builder, string title, IEnumerable<string> lines)
    {
        builder.AppendLine($"## {title}");
        builder.AppendLine();
        List<string> items = lines.Where(line => !string.IsNullOrWhiteSpace(line)).Distinct().OrderBy(line => line).ToList();
        if (items.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (string item in items)
            {
                builder.AppendLine($"- {item}");
            }
        }

        builder.AppendLine();
    }

    private sealed class MapContext
    {
        public readonly Dictionary<string, Tilemap> Tilemaps;
        public readonly AssetLibrary Library;
        public readonly TileSet Tiles;
        public readonly DemoReport Report;
        public readonly System.Random Random;
        public readonly bool[,] Road = new bool[MapWidth, MapHeight];
        public readonly bool[,] Water = new bool[MapWidth, MapHeight];
        public readonly bool[,] MainPath = new bool[MapWidth, MapHeight];
        public readonly bool[,] Occupied = new bool[MapWidth, MapHeight];
        public readonly List<TileBase> DecalVariants;

        public MapContext(Dictionary<string, Tilemap> tilemaps, AssetLibrary library, TileSet tiles, DemoReport report, System.Random random)
        {
            Tilemaps = tilemaps;
            Library = library;
            Tiles = tiles;
            Report = report;
            Random = random;
            DecalVariants = library.FindTiles("Decals").Concat(library.FindTiles("Road", "crack", "detail", "drain")).Distinct().ToList();
        }
    }

    private sealed class TileSet
    {
        public TileBase Grass;
        public TileBase Forest;
        public TileBase Dirt;
        public TileBase Road;
        public TileBase Sidewalk;
        public TileBase Curb;
        public TileBase Sand;
        public TileBase Water;
        public TileBase Decal;
        public TileBase Collision;
        public bool HasWater => Water != null;

        public static TileSet Resolve(AssetLibrary library, DemoReport report)
        {
            TileSet set = new TileSet
            {
                Grass = library.FindTile(report, "Grass", "grass", new[] { "grass", "center" }, new string[0]),
                Forest = library.FindTile(report, "Forest", "forest", new[] { "forest" }, new[] { "Grass" }),
                Dirt = library.FindTile(report, "Dirt", "dirt path", new[] { "dirt", "path" }, new[] { "VillagePlaza", "Grass" }),
                Road = library.FindTile(report, "Road", "road", new[] { "road", "center" }, new string[0]),
                Sidewalk = library.FindTile(report, "Sidewalk", "sidewalk", new[] { "sidewalk" }, new[] { "Road", "Grass" }),
                Curb = library.FindTile(report, "Curb", "curb", new[] { "curb" }, new[] { "Sidewalk", "Road" }),
                Sand = library.FindTile(report, "Sand", "sand", new[] { "sand" }, new[] { "Grass" }),
                Water = library.FindTile(report, "Water", "water", new[] { "water" }, new[] { "Sand" }),
                Decal = library.FindTile(report, "Decals", "decal", new[] { "decal" }, new[] { "Road" }),
                Collision = library.FindTile(report, "Collision", "collision", new[] { "collision" }, new string[0])
            };

            return set;
        }

        public TileBase GetFallbackTile(string category)
        {
            switch (category)
            {
                case "Forest":
                    return Forest ?? Grass;
                case "Dirt":
                case "VillagePlaza":
                    return Dirt ?? Grass;
                case "Road":
                case "Road_Marking":
                    return Road;
                case "Sidewalk":
                    return Sidewalk ?? Road ?? Grass;
                case "Curb":
                    return Curb ?? Sidewalk ?? Road;
                case "Sand":
                    return Sand ?? Grass;
                case "Water":
                    return Water;
                case "Decals":
                    return Decal;
                case "Collision":
                    return Collision;
                case "Grass":
                default:
                    return Grass;
            }
        }
    }

    private sealed class AssetLibrary
    {
        private readonly List<TileAsset> tiles;
        private readonly List<PrefabAsset> prefabs;
        private readonly Dictionary<string, TileBase> tileQueryCache = new Dictionary<string, TileBase>();

        private AssetLibrary(List<TileAsset> tiles, List<PrefabAsset> prefabs)
        {
            this.tiles = tiles;
            this.prefabs = prefabs;
        }

        public static AssetLibrary Load(DemoReport report)
        {
            List<TileAsset> loadedTiles = new List<TileAsset>();
            HashSet<string> loadedTilePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string root in TileRoots)
            {
                if (!Directory.Exists(root))
                {
                    continue;
                }

                foreach (string rawPath in Directory.GetFiles(root, "*.asset", SearchOption.AllDirectories))
                {
                    string path = NormalizePath(rawPath);
                    if (!loadedTilePaths.Add(path))
                    {
                        continue;
                    }

                    TileBase tile = AssetDatabase.LoadAssetAtPath<TileBase>(path);
                    if (tile != null)
                    {
                        loadedTiles.Add(new TileAsset(path, tile));
                    }
                }
            }

            List<PrefabAsset> loadedPrefabs = new List<PrefabAsset>();
            HashSet<string> loadedPrefabPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string root in PrefabRoots)
            {
                if (!Directory.Exists(root))
                {
                    continue;
                }

                foreach (string rawPath in Directory.GetFiles(root, "*.prefab", SearchOption.AllDirectories))
                {
                    string path = NormalizePath(rawPath);
                    if (!loadedPrefabPaths.Add(path))
                    {
                        continue;
                    }

                    GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    if (prefab != null)
                    {
                        loadedPrefabs.Add(new PrefabAsset(path, prefab));
                    }
                }
            }

            report.AvailableTileCategories.AddRange(loadedTiles.Select(tile => tile.Category).Distinct().OrderBy(category => category));
            report.AvailablePrefabCategories.AddRange(loadedPrefabs.Select(prefab => $"{prefab.Kind}: {prefab.Category}").Distinct().OrderBy(category => category));
            RecordMissingImportantCategories(report, loadedTiles, loadedPrefabs);

            return new AssetLibrary(loadedTiles, loadedPrefabs);
        }

        public TileBase FindTile(DemoReport report, string category, string label, string[] requiredTokens, string[] fallbackCategories)
        {
            string cacheKey = $"{category}|{label}|{string.Join(",", requiredTokens)}|{string.Join(",", fallbackCategories)}";
            if (tileQueryCache.TryGetValue(cacheKey, out TileBase cached))
            {
                return cached;
            }

            List<TileAsset> candidates = FindTileAssets(category, requiredTokens);
            if (candidates.Count > 0)
            {
                TileAsset selected = candidates[0];
                tileQueryCache[cacheKey] = selected.Tile;
                return selected.Tile;
            }

            List<TileAsset> categoryFallbacks = FindTileAssets(category, new string[0]);
            if (categoryFallbacks.Count > 0)
            {
                TileAsset fallback = categoryFallbacks[0];
                report.FallbackTilesUsed.Add($"{label}: used {fallback.Path} from {category} because exact tokens were missing.");
                tileQueryCache[cacheKey] = fallback.Tile;
                return fallback.Tile;
            }

            foreach (string fallbackCategory in fallbackCategories)
            {
                List<TileAsset> fallbackCandidates = FindTileAssets(fallbackCategory, requiredTokens);
                if (fallbackCandidates.Count == 0)
                {
                    fallbackCandidates = FindTileAssets(fallbackCategory, new string[0]);
                }

                if (fallbackCandidates.Count > 0)
                {
                    TileAsset fallback = fallbackCandidates[0];
                    report.FallbackTilesUsed.Add($"{label}: used {fallback.Path} from fallback category {fallbackCategory}.");
                    tileQueryCache[cacheKey] = fallback.Tile;
                    return fallback.Tile;
                }
            }

            report.RecordMissingTile(category, label);
            tileQueryCache[cacheKey] = null;
            return null;
        }

        public List<TileBase> FindTiles(string category, params string[] tokens)
        {
            return FindTileAssets(category, tokens).Select(asset => asset.Tile).Distinct().ToList();
        }

        private List<TileAsset> FindTileAssets(string category, IEnumerable<string> tokens)
        {
            string[] normalizedTokens = tokens == null ? new string[0] : tokens.Where(token => !string.IsNullOrWhiteSpace(token)).Select(Normalize).ToArray();
            List<TileAsset> categoryAssets = tiles
                .Where(tile => string.Equals(tile.Category, category, StringComparison.OrdinalIgnoreCase))
                .ToList();

            if (normalizedTokens.Length == 0)
            {
                return categoryAssets.OrderBy(tile => tile.Path).ToList();
            }

            List<TileAsset> exact = categoryAssets
                .Where(tile => normalizedTokens.All(tile.SearchText.Contains))
                .OrderByDescending(tile => tile.Score(normalizedTokens))
                .ThenBy(tile => tile.Path)
                .ToList();

            if (exact.Count > 0)
            {
                return exact;
            }

            return categoryAssets
                .Where(tile => normalizedTokens.Any(tile.SearchText.Contains))
                .OrderByDescending(tile => tile.Score(normalizedTokens))
                .ThenBy(tile => tile.Path)
                .ToList();
        }

        public List<PrefabChoice> FindPrefabs(PrefabKind kind, params string[] tokens)
        {
            string[] normalizedTokens = tokens == null ? new string[0] : tokens.Where(token => !string.IsNullOrWhiteSpace(token)).Select(Normalize).ToArray();
            IEnumerable<PrefabAsset> candidates = prefabs.Where(prefab => prefab.Kind == kind);
            if (normalizedTokens.Length > 0)
            {
                candidates = candidates.Where(prefab => normalizedTokens.Any(prefab.SearchText.Contains));
            }

            return candidates
                .OrderByDescending(prefab => prefab.Score(normalizedTokens))
                .ThenBy(prefab => prefab.Path)
                .Select(prefab => prefab.ToChoice())
                .ToList();
        }

        private static void RecordMissingImportantCategories(DemoReport report, List<TileAsset> loadedTiles, List<PrefabAsset> loadedPrefabs)
        {
            string[] importantTiles =
            {
                "Grass", "Forest", "Dirt", "VillagePlaza", "Sand", "Water", "Road", "Road_Marking", "Sidewalk", "Curb", "Collision"
            };

            foreach (string category in importantTiles)
            {
                if (!loadedTiles.Any(tile => string.Equals(tile.Category, category, StringComparison.OrdinalIgnoreCase)))
                {
                    report.MissingImportantCategories.Add($"Tile: {category}");
                }
            }

            if (!loadedPrefabs.Any(prefab => prefab.Kind == PrefabKind.Prop && prefab.SearchText.Contains("tree")))
            {
                report.MissingImportantCategories.Add("Prop: tree");
            }

            if (!loadedPrefabs.Any(prefab => prefab.Kind == PrefabKind.Prop && prefab.SearchText.Contains("palm")))
            {
                report.MissingImportantCategories.Add("Prop: palm");
            }

            if (!loadedPrefabs.Any(prefab => prefab.Kind == PrefabKind.Building && prefab.SearchText.Contains("garage")))
            {
                report.MissingImportantCategories.Add("Building: garage");
            }
        }

        private static string NormalizePath(string path)
        {
            return path.Replace('\\', '/');
        }
    }

    private sealed class TileAsset
    {
        public readonly string Path;
        public readonly string SearchText;
        public readonly string Category;
        public readonly TileBase Tile;

        public TileAsset(string path, TileBase tile)
        {
            Path = path;
            Tile = tile;
            SearchText = Normalize($"{path} {System.IO.Path.GetFileNameWithoutExtension(path)}");
            Category = DetermineTileCategory(path);
        }

        public int Score(IEnumerable<string> normalizedTokens)
        {
            int score = 0;
            foreach (string token in normalizedTokens)
            {
                if (SearchText.Contains(token))
                {
                    score += 10;
                }
            }

            return score;
        }

        private static string DetermineTileCategory(string path)
        {
            string text = Normalize(path);
            if (text.Contains("road_marking") || text.Contains("roadmarking") || text.Contains("crosswalk") || text.Contains("parking_line") || text.Contains("road_line") || text.Contains("dash"))
            {
                return "Road_Marking";
            }

            if (text.Contains("villageplaza") || text.Contains("village_plaza") || text.Contains("plaza"))
            {
                return "VillagePlaza";
            }

            if (text.Contains("forest"))
            {
                return "Forest";
            }

            if (text.Contains("dirt") || text.Contains("path"))
            {
                return "Dirt";
            }

            if (text.Contains("sidewalk"))
            {
                return "Sidewalk";
            }

            if (text.Contains("curb") || text.Contains("kerb"))
            {
                return "Curb";
            }

            if (text.Contains("sand") || text.Contains("beach"))
            {
                return "Sand";
            }

            if (text.Contains("water") || text.Contains("ocean") || text.Contains("pond") || text.Contains("shore") || text.Contains("foam"))
            {
                return "Water";
            }

            if (text.Contains("decal") || text.Contains("oil") || text.Contains("stain") || text.Contains("moss") || text.Contains("leaf"))
            {
                return "Decals";
            }

            if (text.Contains("collision") || text.Contains("blocker"))
            {
                return "Collision";
            }

            if (text.Contains("road"))
            {
                return "Road";
            }

            return "Grass";
        }
    }

    private sealed class PrefabAsset
    {
        public readonly string Path;
        public readonly string SearchText;
        public readonly string Category;
        public readonly GameObject Prefab;
        public readonly PrefabKind Kind;
        public readonly bool HasCollider;

        public PrefabAsset(string path, GameObject prefab)
        {
            Path = path;
            Prefab = prefab;
            SearchText = Normalize($"{path} {System.IO.Path.GetFileNameWithoutExtension(path)}");
            string normalizedPath = path.Replace('\\', '/');
            Kind = normalizedPath.Contains("/Buildings/") ? PrefabKind.Building : PrefabKind.Prop;
            Category = DeterminePrefabCategory(normalizedPath, Kind);
            HasCollider = prefab.GetComponent<Collider2D>() != null;
        }

        public PrefabChoice ToChoice()
        {
            return new PrefabChoice(Prefab, Kind, Category, Path, HasCollider);
        }

        public int Score(IEnumerable<string> normalizedTokens)
        {
            int score = 0;
            foreach (string token in normalizedTokens)
            {
                if (SearchText.Contains(token))
                {
                    score += 10;
                }
            }

            return score;
        }

        private static string DeterminePrefabCategory(string path, PrefabKind kind)
        {
            string marker = kind == PrefabKind.Building ? "/Buildings/" : "/Props/";
            int markerIndex = path.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
            if (markerIndex >= 0)
            {
                string remainder = path.Substring(markerIndex + marker.Length);
                int slash = remainder.IndexOf('/');
                if (slash > 0)
                {
                    return remainder.Substring(0, slash);
                }
            }

            return kind == PrefabKind.Building ? "Building" : "Prop";
        }
    }

    private readonly struct PrefabChoice
    {
        public static readonly PrefabChoice Invalid = new PrefabChoice(null, PrefabKind.Prop, string.Empty, string.Empty, false);

        public readonly GameObject Prefab;
        public readonly PrefabKind Kind;
        public readonly string Category;
        public readonly string Path;
        public readonly bool HasCollider;
        public bool IsValid => Prefab != null;

        public PrefabChoice(GameObject prefab, PrefabKind kind, string category, string path, bool hasCollider)
        {
            Prefab = prefab;
            Kind = kind;
            Category = category;
            Path = path;
            HasCollider = hasCollider;
        }
    }

    private sealed class DemoReport
    {
        public int PropsPlaced;
        public int BuildingsPlaced;
        public readonly Dictionary<string, HashSet<Vector3Int>> TilesPaintedByLayer = new Dictionary<string, HashSet<Vector3Int>>(StringComparer.OrdinalIgnoreCase);
        public readonly Dictionary<string, int> PropsPlacedByCategory = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        public readonly Dictionary<string, int> BuildingsPlacedByCategory = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        public readonly List<string> AvailableTileCategories = new List<string>();
        public readonly List<string> AvailablePrefabCategories = new List<string>();
        public readonly List<string> MissingImportantCategories = new List<string>();
        public readonly List<string> MissingTileCategories = new List<string>();
        public readonly List<string> MissingPrefabCategories = new List<string>();
        public readonly List<string> FallbackTilesUsed = new List<string>();
        public readonly List<string> SkippedPlacements = new List<string>();
        public readonly List<string> SkippedAreas = new List<string>();
        public readonly List<string> SceneObjectsMoved = new List<string>();
        public readonly List<string> Warnings = new List<string>();
        private readonly HashSet<string> missingLayers = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> singleVariantWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> missingTileWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> missingPrefabWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        public void RecordTilePainted(string layerName, Vector3Int position)
        {
            if (!TilesPaintedByLayer.TryGetValue(layerName, out HashSet<Vector3Int> positions))
            {
                positions = new HashSet<Vector3Int>();
                TilesPaintedByLayer[layerName] = positions;
            }

            positions.Add(position);
        }

        public void RecordMissingLayer(string layerName)
        {
            if (missingLayers.Add(layerName))
            {
                Warnings.Add($"Tilemap layer missing or unavailable: {layerName}");
            }
        }

        public void RecordSingleVariant(string category, IEnumerable<string> keywords)
        {
            string key = $"{category} {string.Join(" ", keywords ?? new string[0])}";
            if (singleVariantWarnings.Add(key))
            {
                Warnings.Add($"Only one tile variant available for {key}; repetition may still be visible.");
            }
        }

        public void RecordSinglePrefabVariant(PrefabKind kind, string label)
        {
            string key = $"{kind}: {label}";
            if (singleVariantWarnings.Add(key))
            {
                Warnings.Add($"Only one prefab variant available for {key}; placement variation is limited.");
            }
        }

        public void RecordMissingTile(string category, string label)
        {
            string key = $"{category} ({label})";
            if (missingTileWarnings.Add(key))
            {
                MissingTileCategories.Add(key);
            }
        }

        public void RecordMissingPrefab(PrefabKind kind, string label)
        {
            string key = $"{kind}: {label}";
            if (missingPrefabWarnings.Add(key))
            {
                MissingPrefabCategories.Add(key);
            }
        }

        public void Increment(Dictionary<string, int> counts, string key)
        {
            if (string.IsNullOrWhiteSpace(key))
            {
                key = "Unknown";
            }

            counts.TryGetValue(key, out int count);
            counts[key] = count + 1;
        }
    }

    private enum PrefabKind
    {
        Prop,
        Building
    }

    private static string Normalize(string text)
    {
        return (text ?? string.Empty).Replace('\\', '/').Replace("-", "_").Replace(" ", "_").ToLowerInvariant();
    }
}
#endif
